---
- hosts: all
  become: true
  tasks:
    - name: ensure repository key is installed
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: ensure docker registry is available
      apt_repository: repo='deb https://download.docker.com/linux/ubuntu bionic stable' state=present

    - name: ensure docker and dependencies are installed
      apt: name=docker-ce update_cache=yes

    - service: name=docker state=restarted

    - name: Clone github repository
      git:
        repo: https://github.com/climatenews/services.git
        dest: /home/ubuntu/services/
        clone: yes
        update: yes

     


# TODO
## create swarm
# sudo docker swarm init
# copy .env.dev file
## run swarm
# env $(cat .env.dev | xargs) docker stack deploy --compose-file docker-compose.yaml climate_news_stack
